# Write a function so that the columns of the output matrix are powers of the input vector. The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

### HINT: Such a matrix with a geometric progression in each row is named for Alexandre-Theophile Vandermonde.

In [1]:
import numpy as np

In [2]:
def atv(inp,n,order):
    output=[]
    if order==False:
        for i in inp:
            for j in range(n):
                t=i**(n-j-1)
                output.append(t)
    elif order==True:
        for i in inp:
            for j in range(n):
                t=i**j
                output.append(t)
    return np.asarray(output).reshape(inp.size,n)

In [3]:
inp = np.array([1,2,3,4,5])
print(atv(inp,5,False))

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


# Write a function to find moving average in an array over a window: Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [4]:
def moving_avg(inp,window):
    m_avg=[]
    k=len(inp)-window+1
    for i in range(k):
        m_avg.append(round(np.sum(inp[i:(window+i)])/window,2))
    print(m_avg)

In [5]:
i=[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
moving_avg(i,3)

[5.0, 4.67, 5.67, 6.67, 9.67, 28.67, 49.33, 72.67, 84.0, 93.33, 116.33]
